micronaut:
  application:
    name: dscatalogKotlin
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db_dscatalog?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: devjs
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
